i3/.config/i3/config
* Replace `bindsym` with `bindcode` where necessary (where letters where
used).
* Set all letters with their keycodes as variables to ease up future
development.
close #9
=> Change syms to keycodes

i3/.config/i3/config
=> Add "us" layout before locking screen

i3/.config/i3/config, polybar/.config/polybar/config, polybar/.config/polybar/launch.sh, ranger/.config/ranger/bookmarks, ranger/.config/ranger/commands.py, ranger/.config/ranger/commands_full.py, ranger/.config/ranger/history, ranger/.config/ranger/rc.conf, ranger/.config/ranger/rifle.conf, ranger/.config/ranger/scope.sh, ranger/.config/ranger/tagged, scripts/camtoggle.sh, scripts/layout-change.sh, scripts/polybar/archupdates.sh, scripts/polybar/openweathermap-simple-icon.sh, scripts/polybar/openweathermap-simple-text.sh, scripts/polybar/spotify.sh, scripts/save-current-window-to-clipboard.sh, scripts/save-current-window.sh, scripts/screencast.sh, zsh/.zshrc
* Add scripts for polybar that do the following:
- Shows arch updates (pacman/aur).
- Shows weather from `openweathermap`.
- Shows spotify current song (also able to toggle play/pause on click)
* Add scripts that:
- Saves the current window to clipboard (img).
- Saves the current window to a file under `~/Pictures/` (img).
- Toggles web camera and puts on bottom right corner.
* Ranger:
- Add ranger to stow directory structure.
=> Introduce polybar

polybar/.config/polybar/config, polybar/.config/polybar/launch.sh, polybar/.config/polybar/readme.md, readme.md, scripts/screens/laptop-screen.sh, scripts/screens/one-screen.sh
* Use multiple config sets on polybar. Each one will handle a screen
separately.
* Add a dynamic way to detect if an external display is present.
* Update readmes.
* Update screens' scripts.
closes #15
=> Update polybar configuration

tmux/.tmux.conf
=> Add zero delay for esc inside tmux

tmux/.tmux.conf, zsh/.zshrc
=> Change `TERM` inside tmux

scripts/save-active-screen.sh, scripts/save-current-window-to-clipboard.sh, scripts/save-current-window.sh, scripts/screencast.sh, scripts/screenshot_region_save.sh, scripts/screenshot_region_to_clipboard.sh, scripts/screenshot_upload_to_imgur.sh
=> Change any date `:` to `-`

homeconfig/.fehbg, i3/.config/i3/config, install.sh, scripts/imgur.sh, scripts/rofi/rofi-emoji-launch.sh, scripts/rofi/rofi-emoji.sh
* Reorder imgur xclip.
* Add emoji script to fetch emojis once. Also this will be used to fuzzy
search emojis through rofi 🎉.
* Change scale in feh.
=> Add emoji finder through rofi

polybar/.config/polybar/config, scripts/camtoggle.sh, scripts/polybar/pulse-input.sh, scripts/unsplash-generator.sh
* Configure mic for polybar to toggle mute and specify the input volume
=> Add mic icon to polybar

.gitmodules, homeconfig/.fehbg, homeconfig/.zshrc, ranger/.config/ranger/rc.conf
=> Remove specific username

dunst/.config/dunst/dunstrc
=> Add missing paths for dunst

homeconfig/.bmdirs, homeconfig/.bmfiles, nvim/.config/nvim/init.vim, ranger/.config/ranger/rifle.conf
* Update relevant files if they are edited on nvim
=> Change way of defining shortcuts for ranger

etcconfig/etc/X11/xorg.conf.d/00-keyboard.conf, etcconfig/etc/default/tlp, etcconfig/etc/sway/config.d/10-systemd, etcconfig/etc/systemd/logind.conf, etcconfig/etc/systemd/system/suspend@.service, etcconfig/etc/systemd/user/sway-session.target
* Move keyboard, tlp to stow
* Move logind conf and suspend services to stow
* Use a systemd service to load sway env vars
close #55
=> feat: Add etc config

sway/.config/sway/config, sway/.config/sway/config.d/app-directives.conf, sway/.config/sway/config.d/startup.conf
=> fix: Workspace assignments

sway/.config/sway/config.d/idle.conf
* Handle idle with these steps:
* If audio is playing it won't execute the idle steps
* First dim the screen
* Then lock it
* Then turn it off 🙈
* Aaaand suspend
* Make sure that screen is on when resuming
close #63
=> feat: Update sway-idle

scripts/custom-lock, swaylock/.config/swaylock/config
=> chore: Put config of swaylock in a file

etcconfig/etc/bluetooth/main.conf
=> chore: Add bluetooth config

homeconfig/.profile, i3/.config/i3/config, i3/.config/i3/config.d/0vars.conf, i3/.config/i3/config.d/app-directives.conf, i3/.config/i3/config.d/appearance.conf, i3/.config/i3/config.d/keybindings.conf, i3/.config/i3/config.d/modes.conf, i3/.config/i3/config.d/startup.conf, scripts/i3commands/i3reload, scripts/i3commands/i3restart
* Separate i3 based on scope to smaller files
* Add i3reload and i3restart to override the i3 config by combining the
`i3/config.d/*.conf` files
close #72
=> feat: Split i3 into config files

dunst/.config/dunst/dunstrc, mako/.config/mako/config
=> style: Make notifications transparent

polybar/.config/polybar/config, polybar/.config/polybar/launch.sh, scripts/polybar/battery-combined
=> feat: Make polybar launch a bit dunamic

polybar/.config/polybar/launch.sh
=> fix: Duplicate polybar

config-dotfiles/.config/compton.conf
=> chore: Compton update

scripts/idle-hook
=> fix: Restore brightness properly idlehook

scripts/rofi/rofi-emoji-launch
=> fix: Rofi emoji paste

i3/.config/i3/config.d/keybindings.conf
* Pass correct argument to `handle-mic` script
close #93
=> fix: Handle mic levels

scripts/idle-hook
=> fix: Restore brightness on idle-hook

scripts/polybar/spotify
=> fix: Special characters in spotify polybar

waybar/.config/waybar/style.css
=> chore: Use same fonts on waybar from polybar

scripts/wayland/wl-screencast
=> chore: Save wayland recordings to Videos dir

scripts/wayland/wl-monitor-input-layout, waybar/.config/waybar/config, waybar/.config/waybar/style.css
=> feat: Add keyboard layout to waybar

scripts/wayland/color-picker
=> feat: Color picker for sway

scripts/brightness, wm/.config/sway/config.d/keybindings.conf
=> feat: Visual feedback on brightness change

scripts/take-screenshot
=> feat: Update `take-screenshot` for wayland window

scripts/cronjobs/random-wallpaper
=> feat (random-wallpaper): add gnome support
